receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  jaeger:
    endpoint: "jaeger:14250"
    insecure: true
  googlecloud:
    project: your-project-id

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger, googlecloud]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
